# Generated by Django 4.1.7 on 2023-06-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notifications',
            name='color',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
