# Generated by Django 4.2.7 on 2023-11-07 02:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_notification_options_pwtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
