# Generated by Django 4.1.7 on 2023-06-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='slug',
            new_name='l_slug',
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
