# Generated by Django 4.1.7 on 2023-06-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_slug_lesson_l_slug_lesson_is_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='l_slug',
            new_name='slug',
        ),
    ]
