# Generated by Django 4.1.7 on 2023-06-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_lesson_student_completed_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
